[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
folio = "DTF4yDGBkXJ25Ech1JVQpfwVb1vqYW4RJs5SuGNWdDev"
folio_admin = "RsHWkAsrWvntjhWgMT1uBLJJea9TSjDhsx8j3DHVDEv"
rewards = "7GiMvNDHVY8PXWQLHjSf1REGKpiDsVzRr4p7Y3xGbSuf"

[programs.devnet]
folio = "DTF4yDGBkXJ25Ech1JVQpfwVb1vqYW4RJs5SuGNWdDev"
folio_admin = "RsHWkAsrWvntjhWgMT1uBLJJea9TSjDhsx8j3DHVDEv"
rewards = "7GiMvNDHVY8PXWQLHjSf1REGKpiDsVzRr4p7Y3xGbSuf"

[programs.mainnet]
folio = "DTF4yDGBkXJ25Ech1JVQpfwVb1vqYW4RJs5SuGNWdDev"
folio_admin = "RsHWkAsrWvntjhWgMT1uBLJJea9TSjDhsx8j3DHVDEv"
rewards = "7GiMvNDHVY8PXWQLHjSf1REGKpiDsVzRr4p7Y3xGbSuf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "tsc && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests-ts/tests-*.ts"
# Needs to be serial https://github.com/kevinheavey/solana-bankrun/issues/2
test-bankrun = "tsc && yarn ts-mocha -p ./tsconfig.json -t 1000000 --serial --recursive tests-ts/bankrun/test-runner.ts"
# Anchor struggles with lock file version 4, even if it's locked at verison 3 in config.toml
# seems like anchor changes it sometimes
post-build = "cargo update --package cargo-lock --precise \"3\""
