[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
folio = "n6sR7Eg5LMg5SGorxK9q3ZePHs9e8gjoQ7TgUW2YCaG"
dtfs = "7ZqvG9KKhzA3ykto2WMYuw3waWuaydKwYKHYSf7SiFbn"
[programs.devnet]
folio = "n6sR7Eg5LMg5SGorxK9q3ZePHs9e8gjoQ7TgUW2YCaG"
dtfs = "7ZqvG9KKhzA3ykto2WMYuw3waWuaydKwYKHYSf7SiFbn"
[programs.mainnet]
folio = "n6sR7Eg5LMg5SGorxK9q3ZePHs9e8gjoQ7TgUW2YCaG"
dtfs = "7ZqvG9KKhzA3ykto2WMYuw3waWuaydKwYKHYSf7SiFbn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "tsc && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests-ts/**/tests-dtfs.ts"
# Needs to be serial https://github.com/kevinheavey/solana-bankrun/issues/2
test-bankrun = "tsc && yarn run ts-mocha -p ./tsconfig.json -t 1000000 --serial tests-ts/bankrun/tests/*.ts"
