[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dtfs = "7ZqvG9KKhzA3ykto2WMYuw3waWuaydKwYKHYSf7SiFbn"
folio = "n6sR7Eg5LMg5SGorxK9q3ZePHs9e8gjoQ7TgUW2YCaG"
[programs.devnet]
dtfs = "7ZqvG9KKhzA3ykto2WMYuw3waWuaydKwYKHYSf7SiFbn"
folio = "n6sR7Eg5LMg5SGorxK9q3ZePHs9e8gjoQ7TgUW2YCaG"
[programs.mainnet]
dtfs = "7ZqvG9KKhzA3ykto2WMYuw3waWuaydKwYKHYSf7SiFbn"
folio = "n6sR7Eg5LMg5SGorxK9q3ZePHs9e8gjoQ7TgUW2YCaG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "tsc && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/tests-*.ts"
