[workspace]
members = [
    "programs/folio",
    "programs/folio-admin",
    "programs/rewards",
    "tests",
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = { version = "=0.30.1" }
anchor-spl = "=0.30.1"
bytemuck = "=1.20.0"
spl-math = { version = "=0.2.0", features = ["no-entrypoint"] }

[workspace.lints.rust]
unexpected_cfgs = { level = "allow" }
ambiguous_glob_reexports = { level = "allow" }