[target.'cfg(all())']
rustflags = [
    "-A", "ambiguous_glob_reexports",
]

[lock]
version = "3"

[target.'cfg(coverage)']
rustflags = [
    "-Cinstrument-coverage",
    "-Clink-dead-code",
    "-Ccodegen-units=1",
]

[env]
CARGO_LLVM_COV = "1"