[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
name = "shared"
crate-type = ["lib"]

[dependencies]
anchor-lang = "=0.30.1"
bytemuck = "=1.20.0"
spl-math = { version = "=0.2.0", features = ["no-entrypoint"] }
solana-program = "=1.18.26"

[build-dependencies]
dotenv = "0.15"
