name: Solana Program CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 2.1.0
  ANCHOR_VERSION: 0.30.1
  ADMIN_PUBKEY: AXF3tTrMUD5BLzv5Fmyj63KXwvkuGdxMQemSJHtTag4j
  SPL_GOVERNANCE_PROGRAM_ID: HwXcHGabc19PxzYFVSfKvuaDSNpbLGL8fhVtkcTyEymj

jobs:
  setup-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Solana and Anchor
        id: cache-check
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/solana
            ~/.cargo/bin/anchor
            ~/.cargo/bin/avm
            ~/.avm
          key: ${{ runner.os }}-tools-${{ env.SOLANA_VERSION }}-${{ env.ANCHOR_VERSION }}

      - name: Install Solana
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v${{ env.SOLANA_VERSION }}/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Install Anchor
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install ${{ env.ANCHOR_VERSION }}
          avm use ${{ env.ANCHOR_VERSION }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.83.0"
          components: rustfmt, clippy

      - name: Rust Format Check
        run: cargo fmt --all -- --check

      - name: Clippy Check
        run: |
          cargo clippy -- \
            -A ambiguous_glob_reexports \
            -D warnings

  build-dependencies:
    needs: setup-tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.83.0"

      - name: Restore cached tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/solana
            ~/.cargo/bin/anchor
            ~/.cargo/bin/avm
            ~/.avm
          key: ${{ runner.os }}-tools-${{ env.SOLANA_VERSION }}-${{ env.ANCHOR_VERSION }}

      - name: Add Solana to PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Just
        run: cargo install just

      - name: Build SPL
        run: |
          # Build SPl governance program and DTF programs
          just build-local

      - name: Upload built programs
        uses: actions/upload-artifact@v4
        with:
          name: built-programs
          path: |
            tests-ts/programs/*.so
            target/deploy/*.so
            target/types/**/*.ts
            target/idl/*.json
          retention-days: 1

  unit-tests:
    needs: [build-dependencies, setup-tools]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.83.0"

      - name: Restore cached tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/solana
            ~/.cargo/bin/anchor
            ~/.cargo/bin/avm
            ~/.avm
          key: ${{ runner.os }}-tools-${{ env.SOLANA_VERSION }}-${{ env.ANCHOR_VERSION }}

      - name: Add Solana to PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Download built programs
        uses: actions/download-artifact@v4
        with:
          name: built-programs
          path: .

      - name: List downloaded files
        run: |
          echo "Contents of target/types:"
          ls -R target/types || true

      - name: Create Solana Config Dir
        run: |
          mkdir -p /home/runner/.config/solana
          solana-keygen new --no-bip39-passphrase -o /home/runner/.config/solana/id.json

      - name: Cargo Test
        run: cargo test

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage report
        continue-on-error: true
        run: |
          cargo tarpaulin --workspace \
          --exclude-files \
          "programs/*/src/instructions/*" \
          "programs/*/src/external/*" \
          "programs/*/src/**/events.rs" \
          "programs/*/src/**/state.rs" \
          "programs/*/src/lib.rs" \
          "programs/*/src/**/errors.rs" \
          --out Html \
          --output-dir target/tarpaulin

  integration-tests:
    needs: [build-dependencies, setup-tools]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install npm dependencies
        run: |
          npm install
          npm install @metaplex-foundation/amman 
          npm install -g @metaplex-foundation/amman
          npx amman --version  # Verify installation

      - name: Restore cached tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/solana
            ~/.cargo/bin/anchor
            ~/.cargo/bin/avm
            ~/.avm
          key: ${{ runner.os }}-tools-${{ env.SOLANA_VERSION }}-${{ env.ANCHOR_VERSION }}

      - name: Add Solana to PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Download built programs
        uses: actions/download-artifact@v4
        with:
          name: built-programs
          path: .

      - name: Create Solana Config Dir
        run: |
          mkdir -p /home/runner/.config/solana
          solana-keygen new --no-bip39-passphrase -o /home/runner/.config/solana/id.json

      - name: Bankrun Test
        run: anchor run test-bankrun

      - name: Run Amman Tests
        run: |
          amman start &
          AMMAN_PID=$!
          sleep 15

          anchor test --skip-local-validator --skip-deploy --skip-build
          TEST_EXIT_CODE=$?

          kill $AMMAN_PID
          exit $TEST_EXIT_CODE
